### ISSUE TITLE
Improve swap state management

### ISSUE THREAD

**Issue by usern3** [KongSwap/kong#192]
Currently the token pairs always reset when navigating away from and back to the swap. It reverts to the ICP/KONG tokens. But, the numbers entered by the user before navigating away from and back to the swap are persisted and remain in the swap box. 

I think this needs 2 things:
- Always reset swap amount to 0 when navigating away from a page.
- Remember the last selected tokens between page navs (just a store, dont persist on reloads)

**Comment by CanerKocak** [comment]
i dont agree with saving the last trade direction, however i do agree with setting the input fields back to 0 again

the reason i dont like saved directions is that adds more complexity to managment of an already complex component

as of now as long as user enters through parameters it will set to those, so instead of doing it in swap maybe we make a middleman function in our "goto" funcs so that when user goes from swap -> earn it will remember a "back" path but even then i dont see it as a useful thing imo since swap needs to read from a more persistent source to know what to do in the select token area

if this is really really a thing, it we should atleast discus it more to figure out a clean, non memory leaking, fast and intuitive way of allowing persistant token selectors, i think time is better spend just resetting input amounts + integrating oisy instead of rethinking token selectors logic

**Comment by CanerKocak** [comment]
https://github.com/KongSwap/kong/pull/224/commits/fe77387ddcc437e9b3f3825a8005f8aa3d798ebc
